//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirth.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMSMessageLog
    {
        public int PMSMessageID { get; set; }
        public int UpdateStatusID { get; set; }
        public int NumberOfAttempt { get; set; }
        public string Status { get; set; }
        public System.DateTime LastTriedTime { get; set; }
    }
}
