//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAPIService.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BacktalkDBEntities : DbContext
    {
        public BacktalkDBEntities()
            : base("name=BacktalkDBEntities")
        {
        }

        public BacktalkDBEntities(string connString) : base(connString)
        {
            //this.Database.Connection.ConnectionString = connString;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IFMessageLog> IFMessageLogs { get; set; }
        public DbSet<Pharmacist> Pharmacists { get; set; }
        public DbSet<PMSMessageLog> PMSMessageLogs { get; set; }
        public DbSet<StatusUpdate> StatusUpdates { get; set; }
    }
}
