//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAPIService.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BacktalkDBEntities : DbContext
    {
        public BacktalkDBEntities()
            : base("name=BacktalkDBEntities")
        {
        }

        public BacktalkDBEntities(string ConnString)
            : base(ConnString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public DbSet<Audit> Audits { get; set; }
        public DbSet<DatabaseConnection> DatabaseConnections { get; set; }
        public DbSet<FileLog> FileLogs { get; set; }
        public DbSet<PMSMessageLog> PMSMessageLogs { get; set; }
        public DbSet<XMLGenerationLog> XMLGenerationLogs { get; set; }
        public DbSet<Pharmacist> Pharmacists { get; set; }
        public DbSet<StatusUpdate> StatusUpdates { get; set; }
        public DbSet<MessageLog> MessageLogs { get; set; }
    }
}
