//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAPIService.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseConnection
    {
        public int DBID { get; set; }
        public string ServerName { get; set; }
        public string DatabaseName { get; set; }
        public string DataBaseType { get; set; }
        public bool Authentication { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
