//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAPIService.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFMessageLog
    {
        public int IFMessageID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Message { get; set; }
        public string MsgRxNumber { get; set; }
        public string MsgPtID { get; set; }
        public string MsgNdc { get; set; }
        public string ResponseMsg { get; set; }
        public string Status { get; set; }
    }
}
