//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAPIService.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacist
    {
        public int Id { get; set; }
        public Nullable<int> PMSID { get; set; }
        public Nullable<int> InspectRxID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Action { get; set; }
    }
}
